### ISSUE TITLE
Setting up a simple connection..

### ISSUE THREAD

**Issue by shadowwolf0189** [TheHolyWaffle/League-of-Legends-XMPP-Chat-Library#14]
Greetings!
I apologize in advance for the sideways question, but you're one of the few people I can find that are continuing work on the XMPP side of League.

I'm trying to setup a basic connection to the chat servers. Here is what I've tried; http://pastie.org/private/qkpvx0jwl3ghclf246sg

However I'm stuck with two errors:
(1) org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: chat.na2.lol.riotgames.com:5223 Exception: null
(2) Server did not report any SASL mechanisms

I should point out that I've tried both na1 and na2. 

Again I apologize for contacting you here but I could not find an e-mail or anything else withwhich to do so. Any help is appreciated! Vielen Dank!

-Steve

**Comment by shadowwolf0189** [comment]
I have done some further testing and moved to testing in Eclipse on my desktop rather than Android Developer Studio.

I downloaded your included JAR file and successfully ran it (verified by running through my friends, printing the names). However I did my best to replicate a simple connection based on your code, and I get an SASL error using the code here: http://pastie.org/private/naypfuktfypqqnwo8uquva

Tried enabling/disabling Compression and SecurityMode.

Relevant error:
org.jivesoftware.smack.sasl.SASLErrorException: SASLError using PLAIN: not-authorized
at org.jivesoftware.smack.SASLAuthentication.authenticate(SASLAuthentication.java:348)
at org.jivesoftware.smack.tcp.XMPPTCPConnection.login(XMPPTCPConnection.java:244)

And the error line is connection.login()

Thanks again in advance for any help!

**Comment by TheHolyWaffle** [comment]
I believe it has to do with Smack (XMPP framework) not fully supporting
Android. A previous user told me that some classes were actually missing if
you would copy my source into a java project (the javax package). Smack
provides an artifact that should support Android:
http://mvnrepository.com/artifact/org.igniterealtime.smack/smack-android

Try adding this to your project.

2015-01-18 13:33 GMT+01:00 shadowwolf0189 <notifications@github.com>:

**Comment by shadowwolf0189** [comment]
I do indeed have it on there already, as I've talked with Flow (the developer of both Smack and aSmack), and he has confirmed that Smack 4.1 fully supports Android.

That said, I've talked with a maker of a League of Legends mobile app, and he said that he actually uses aSmack, a previous version, because of complications with Smack.

Thanks again for your help!

**Comment by Stoyicker** [comment]
I have an Android app (rather ugly right now, but that's not the matter of concern) with a working version of the chat built on top of this library, and yes, I don't use the latest aSmack.
For reference, https://github.com/Stoyicker/LoLin1_old

**Comment by shadowwolf0189** [comment]
I am, without a doubt, in love with you. After 3 days of thinking that my computer would look better thrown through my window, my problem is finally solved.

Best of luck to you in all your future endeavors, friend.

**Comment by Stoyicker** [comment]
You're welcome. Also, quoting #6, for the sake of traceability mostly.
